name: CI

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  - push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'
          cache: 'pip' # caching pip dependencies
      - uses: pre-commit/action@v2.0.3
      - name: Install dependencies
        run: pip install -r requirements.txt

  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Build the Stack
        run: docker-compose -f test.yml build

      - name: Run Django Tests
        run: docker-compose -f test.yml run ftp_server
